const icons = {
    copy: require("./copy.svg"),
    delete: require("./delete.png"),
    checked: require("./checked.svg"),
    networkSelector: require("./network.svg"),
    corporation: require("./coti.svg"),
    helpCircle: require("./help_circle.svg"),
    shen: require("./shen.svg"),
    chart: require("./chart.svg"),
    reserves: require("./reserves.svg"),
    close: require("./close.png"),
    djed: require("./djed.svg"),
    install: require("./install.png"),
    arrowRight: require("./arrow-right.png"),
    arrowBottom: require("./arrow-bottom.png"),
    glass: require("./no-data.svg"),
    separate: require("./separate.png"),
    searchDelete: require("./search-delete.svg"),
    arrowBottomYellow: require("./arrow-bottom-yellow.svg"),
    cardanoChartCoin: require("./cardano.webp"),
    djedChartCoin: require("./djed.webp"),
    vietnameseFlag: require("./vietnam-flag.svg"),
    unitedKingdomFlag: require("./united-kingdom-flag.png"),
    files: {
        defaultFile: require("./file-default.svg"),
    },
    arrowRightPagination: require("./arrow-right-pagination.png"),
    arrowLeftPagination: require("./arrow-left-pagination.png"),
    c2vn: require("./c2vn.png"),
};

export default icons;
